<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ReceiptPrinter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ical.Net" Version="4.3.1" />
  </ItemGroup>

</Project>
